// <auto-generated />
using System;
using EntityNetAzureCorrection1.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EntityNetAzureCorrection1.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20230731134954_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("EntityNetAzureCorrection1.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Pseudo")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Created = new DateTime(2023, 7, 31, 15, 49, 54, 241, DateTimeKind.Local).AddTicks(2279),
                            Email = "User@user.com",
                            Password = "User123=",
                            Pseudo = "UserGuy"
                        },
                        new
                        {
                            Id = 2,
                            Created = new DateTime(2023, 7, 31, 15, 49, 54, 241, DateTimeKind.Local).AddTicks(2319),
                            Email = "Admin@admin.com",
                            Password = "Admin123=",
                            Pseudo = "AdminGuy"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
